config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'games#game_overview'

  get '/games/select_game', to: 'games#select_game'
  post '/games/select', to: 'games#select'

  get '/games/game_overview', to: 'games#game_overview'
  post '/games/overview', to: 'games#overview'

  resources :reviews, only: [:index, :create, :update]

  resources :games, except: [:index] do
    resources :reviews, except: [:create, :update]
  end

  

  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :reviews
    has_many :users, through: :reviews

    validates :name, :description, presence: true
    validates :name, uniqueness: true
    validates :description, length: { in: 20..500 }
    
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    layout "reviews"
    
    def new
        if user_signed_in?
            if current_user.birthday != nil
                if flash[:alert] = current_user.adult
                    redirect_to games_select_game_path
                end
            end
            @game = Game.new
        else
            logged_in
        end
    end

    def create
        game = Game.new(game_params)
        if game.save
            redirect_to new_game_review_path(game.id)
        else 
            flash[:message] = game.e
            redirect_to new_game_path 
        end
    end

    def select_game 
        @games = Game.all   
    end 

    def select 
        redirect_to new_game_review_path(params[:games])
    end
    
    def game_overview
        @games = Game.all
        render layout: "root" unless user_signed_in?
    end

    def overview 
        redirect_to game_path(params[:games])
    end

    def show
        @users = User.all
        @game = Game.find(params[:id])
        #render layout: "root" unless user_signed_in?
        if user_signed_in?
            respond_to do |format|
                format.html {render :show }
                format.json {render json: [@users, @game]}
            end
        else
            respond_to do |format|
                format.html {render layout: "root" }
                format.json {render json: [@users, @game]}
            end
        end
    end    

    def edit
        if user_signed_in? 
            @game = Game.find(params[:id])
            unless current_user == @game.reviews.first.user
                flash[:alert] = "Only the creator of this Game can edit it!"
                redirect_to game_path(@game)
            end
        else 
            logged_in
        end   
    end

    def update
        game = Game.find(params[:id])
        game.update(game_params)
        if game.save
            redirect_to game_path(game)
        else
            flash[:message] = game.e
            redirect_to edit_game_path(game)
        end
    end

    def destroy
        if user_signed_in?
            game = Game.find(params[:id])
            if current_user == game.reviews.first.user
                flash[:alert] = "Your game #{game.name} has successfully been deleted!"
                game.delete
                redirect_to games_game_overview_path
            else 
                flash[:alert] = "Only the Game creator can delete it!"
                redirect_to game_path(game)
            end
        else 
            logged_in
        end
    end

    private
        def game_params
            params.require(:game).permit(:name, :description, :platform, :rating)
        end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for game do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %> <br>

    <%= f.label :description %>
    <%= f.text_area :description %> <br>

    <%= f.label :platform %>
    <%= f.select :platform, (["PC", "PS4", "XBOX", "Other"]) %> <br>

    <%= f.label :rating %>
    <%= f.select :rating, (["Everyone", "Everyone (10+)", "Teen (13+)", "Mature (17+)", "Adults (18+)"]) %> <br>

    <%= f.submit button %>
<% end %>

app/views/games/_selection.html.erb
<h2>Which Game would you like to <%= insert %>?</h2>

<%= form_tag(link) do %>
    <%= select_tag "games", options_from_collection_for_select(games, "id", "name") %>
    <%= submit_tag button, :id => id %>
<% end %>

app/views/games/edit.html.erb
<h2>Edit the Game</h2>

<%= render partial: 'form', locals: { game: @game, button: "Update Game"} %>

app/views/games/game_overview.html.erb


<%= render partial: 'selection', locals: { link: '/games/overview', games: @games, button: "Select Game", id: "submit-game", insert: "see"} %>

<% if !user_signed_in? %>
    <h3>Cannot find what you are looking for? <%= link_to 'Sign Up', new_user_registration_path %> or <%= link_to 'Log In', new_user_session_path %> and create your own Games and Reviews!</h3> 
<% end %>

<div id="js-show-game"></div>

app/views/games/new.html.erb
<h2>Create new Game</h2>

<%= render partial: 'form', locals: { game: @game, button: "Create Game"} %>

app/views/games/oldshow.html.erb
<%= form_tag(games_select_user_path) do %>
    <%= hidden_field_tag 'game', @game.id %>
    <%= select_tag 'user_id', options_from_collection_for_select(@users, "id", "first_name") %>
    <%= submit_tag "Find User" %>
<% end %>

<% if @user %>
    <% @user.reviews.find_all{|r| r.game_id == @game.id}.each do |review| %>
        <div class="review">
            <h3><%= review.title %></h3>
            <h4><%= review.rating %> Star(s) - <%= rec(review) %></h4>
            <p><%= review.content %></p>
            <h5>written by <%= review.user.first_name %></h5>
        </div><br>  
    <% end %>

    <%= button_to 'See All Reviews', game_path(@game), method: :get %>
    
<% else %>
    <% @game.reviews.each do |review| %>
        <div class="review">
            <h3><%= review.title %></h3>
            <h4><%= review.rating %> Star(s) - <%= rec(review) %></h4>
            <p><%= review.content %></p>
            <h5>written by <%= review.user.first_name %></h5>
        </div><br>   
    <% end %>
<% end %>

app/views/games/select_game.html.erb
<%= render partial: 'selection', locals: { link: '/games/select', games: @games, button: "Select Game", id: "submit-game-for-review", insert: "review"} %>

<p><%= button_to 'Create New Game', new_game_path, method: :get %></p>

app/views/games/show.html.erb
<h2><%= @game.name %></h2>
<p>Available for <%= @game.platform %> - <%= @game.rating %></p>
<p><%= @game.description %></p>
<% user = @game.reviews.all.find{|r| r.user == current_user} %>

<% if !user_signed_in? %>
    <h4>Cannot find what you are looking for? <%= link_to 'Sign Up', new_user_registration_path %> or <%= link_to 'Log In', new_user_session_path %> and create your own Games and Reviews!</h4> 
<% elsif @game.reviews.first.user == current_user %>
    <%= button_to 'Edit Game', edit_game_path(@game), method: :get %>
    <%= button_to 'Delete Game', game_path(@game), method: :delete, data: { confirm: 'Are you sure you want to delete this game and all its reviews?' } %>
<% elsif user == nil %>
    <button class="js-new-review" data-id="<%= @game.id %>" type="button">Write Review</button>
<% end %>

<div id="review-form"></div>
<br> <button class="js-reviews" data-id="<%= @game.id %>" type="button">See Reviews</button>
<br>
_________________________________________________________
<br><h2 id="h2-reviews"></h2>

<div id="reviews"></div>