config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'games#game_overview'

  get '/games/select_game', to: 'games#select_game'
  post '/games/select', to: 'games#select'

  get '/games/game_overview', to: 'games#game_overview'
  post '/games/overview', to: 'games#overview'

  resources :reviews, only: [:index, :create, :update]

  resources :games, except: [:index] do
    resources :reviews, except: [:create, :update]
  end

  

  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    require 'pry'
    def index
        if user_signed_in?
            if params[:game_id]
                @reviews = Game.find(params[:game_id]).reviews 
                respond_to do |format|
                    format.html {render :'games/show'}
                    format.json {render json: @reviews}
                end
            else
                @revs = current_user.reviews
                @games = Game.all
                @user = current_user
                respond_to do |format|
                    format.html {render :index}
                    format.json {render json: @revs}
                end
            end
        elsif params[:game_id]
            @reviews = Game.find(params[:game_id]).reviews 
            respond_to do |format|
                format.html {render :'games/show'}
                format.json {render json: @reviews}
            end
        end
    end

    def new
        if user_signed_in?
            @review = Review.new(game_id: params[:game_id], user_id: current_user.id)
            if current_user.birthday != nil
                if flash[:alert] = @review.age_restriction
                    redirect_to root_path
                end
            end
            respond_to do |format|
                format.html {render :new}
                format.json {render json: @review}
            end
        else
            logged_in
        end
    end

    def create
        review = Review.new(review_params)
        #binding.pry
        if review.save
            @game = Game.find(params[:review][:game_id])
            respond_to do |format|
                format.html {render :'games/show'}
                format.json {render json: [review, @game]}
            end
        else
            flash[:message] = review.e
            redirect_to new_game_review_path(review.game.id)
        end 
    end

    def show
        @review = Review.find(params[:id])
        @reviews = current_user.reviews
        respond_to do |format|
            format.html {render :show}
            format.json {render json: @reviews}
        end
    end

    def edit
        if user_signed_in?
            @review = Review.find(params[:id])
            unless current_user == @review.user
                flash[:alert] = "Only the creator of this Review can edit it!"
            redirect_to game_review_path(@review.game, @review)
            end
        else 
            logged_in
        end   
    end

    def update
        review = Review.find(params[:id])
        review.update(review_params)
        if review.save
            redirect_to game_review_path(review.game, review)
        else
            flash[:alert] = review.e
            redirect_to edit_game_review_path(review.game, review)
        end
    end

    def destroy
        if user_signed_in?
            review = Review.find(params[:id])
            if review.user == current_user
                review.delete
                flash[:alert] = "Review has been deleted successfully!"
            else
                flash[:alert] = "You cannot delete someone else's review!"
            end
            redirect_to reviews_path
        else
            logged_in
        end
    end

    private
        def review_params
            params.require(:review).permit(:title, :content, :rating, :recommend, :user_id, :game_id)
        end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
    def rec(review)
        review.recommend ? "Would Recommend" : "Would Not Recommend"
    end
end

app/views/reviews/_form.html.erb
<h2><%= insert %> Review for <%= review.game.name %></h2>

<%= form_for review do |f| %>
    <%= f.hidden_field :game_id %>
    <%= f.hidden_field :user_id %>

    <%= f.label :title %>
    <%= f.text_field :title %> <br>

    <%= f.label :content %>
    <%= f.text_area :content %> <br>

    <%= f.label :rating %>
    <%= f.select :rating, (1..5) %> <br>

    <%= f.label :recommend %>
    <%= f.check_box :recommend %> <br>

    <%= f.submit button %>
<% end %>

app/views/reviews/edit.html.erb
<%= render partial: 'form', locals: { review: @review, button: "Update Review", insert: "Update"} %>

app/views/reviews/game.html.erb
<h3>Which Game would you like to review?</h3>

<!--select game from select field -->
<%= form_tag('/reviews/new', method: :get) do %>
    <%= select_tag "games", options_from_collection_for_select(@games, "id", "name") %>
    <%= submit_tag  "Choose Game" %>
<% end %>

<p><%= button_to 'Create New Game', new_game_path, method: :get %></p>

app/views/reviews/index.html.erb
<h3>Hi <%= @user.first_name.capitalize %>! Here are all the reviews you have written so far</h3>

<%= form_tag games_select_game_path, id: "form" do %>
    <%= hidden_field_tag 'user', @user.id %>
    <%= select_tag 'game_id', options_from_collection_for_select(@games, "id", "name") %>
    <%= submit_tag "Find Review", id: "select-game" %>
<% end %>

<div id="error"></div>

<div id="review-list"> 
  <ul>
    <% @user.reviews.each do |r| %>
      <% unless r.game == nil %>
        <li>
            <%= link_to r.title, game_review_path(r.game, r) %>
            for <%= r.game.name %> <br>
            created at <%= r.created_at.strftime('%A, %b %d, %Y') %>
        </li> 
        <% else %>
      <% end %>
    <% end %>   
  </ul>
</div>

<p><%= button_to 'Create new Review', games_select_game_path, method: :get %></p>

app/views/reviews/new.html.erb
<%= render partial: 'form', locals: { review: @review, button: "Create Review", insert: "Create New"} %>

app/views/reviews/show.html.erb
<% unless @review.id == @reviews[-1].id %>
    <button class="js-next" review-id="<%= @review.id %>" game-id="<%= @review.game_id %>" type="button">Next Review</button>
<% end %>

<h1 id="r-game"><%= @review.game.name.capitalize %></h1>
<div id="review-display">
    <h3 id="r-title"><%= @review.title %></h3>
    <h4 id="r-rating"><%= @review.rating %> Star(s) - <%= rec(@review) %></h4>
    <p id="r-content"><%= @review.content %></p>
</div>

<%= button_to 'Edit Review', edit_game_review_path(@review.game, @review), method: :get, id: "edit-button" %>
<%= button_to 'Delete Review', game_review_path(@review.game, @review), method: :delete, id: "delete-button" %>
<a href="/games/<%= @review.game_id %>", class="show-reviews"><button data-id="<%= @review.game_id %>" type="button">Show All Reviews</button></a>